/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// SysAdminApiService is a service that implements the logic for the SysAdminApiServicer
// This service should implement the business logic for every endpoint for the SysAdminApi API.
// Include any external packages or services that will be required by this service.
type SysAdminApiService struct {
}

// NewSysAdminApiService creates a default api service
func NewSysAdminApiService() SysAdminApiServicer {
	return &SysAdminApiService{}
}

// DeleteAccount - delete school
func (s *SysAdminApiService) DeleteAccount(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteAccount with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteAccount method not implemented")
}

// DeleteSchool - delete school
func (s *SysAdminApiService) DeleteSchool(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteSchool with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteSchool method not implemented")
}

// EditAccount - edit account
func (s *SysAdminApiService) EditAccount(ctx context.Context, accountsAccountBody AccountsAccountBody) (ImplResponse, error) {
	// TODO - update EditAccount with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Account{}) or use other options such as http.Ok ...
	//return Response(200, []Account{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditAccount method not implemented")
}

// EditBuck - edit buck
func (s *SysAdminApiService) EditBuck(ctx context.Context, bucksBuckBody BucksBuckBody) (ImplResponse, error) {
	// TODO - update EditBuck with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Buck{}) or use other options such as http.Ok ...
	//return Response(200, Buck{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditBuck method not implemented")
}

// EditSchool - edit school
func (s *SysAdminApiService) EditSchool(ctx context.Context, schoolsSchoolBody SchoolsSchoolBody) (ImplResponse, error) {
	// TODO - update EditSchool with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []School{}) or use other options such as http.Ok ...
	//return Response(200, []School{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditSchool method not implemented")
}

// GetSchoolUsers - return all users of school
func (s *SysAdminApiService) GetSchoolUsers(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetSchoolUsers with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []UserNoHistory{}) or use other options such as http.Ok ...
	//return Response(200, []UserNoHistory{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSchoolUsers method not implemented")
}

// GetSchools - return all schools
func (s *SysAdminApiService) GetSchools(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetSchools with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseSchools{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseSchools{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSchools method not implemented")
}

// ImpersonateUser - Issue a short-lived JWT (and XSRF token) for user impersonation
func (s *SysAdminApiService) ImpersonateUser(ctx context.Context, requestImpersonate RequestImpersonate) (ImplResponse, error) {
	// TODO - update ImpersonateUser with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseImpersonate{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseImpersonate{}), nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(403, {}) or use other options such as http.Ok ...
	//return Response(403, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ImpersonateUser method not implemented")
}

// MakeAccount - make account
func (s *SysAdminApiService) MakeAccount(ctx context.Context, accountsAccountBody1 AccountsAccountBody1) (ImplResponse, error) {
	// TODO - update MakeAccount with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Account{}) or use other options such as http.Ok ...
	//return Response(200, []Account{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("MakeAccount method not implemented")
}

// MakeSchool - make a new school
func (s *SysAdminApiService) MakeSchool(ctx context.Context, schoolsSchoolBody1 SchoolsSchoolBody1) (ImplResponse, error) {
	// TODO - update MakeSchool with the required logic for this service method.
	// Add api_sys_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse200{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse200{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("MakeSchool method not implemented")
}
