/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TeacherApiService is a service that implements the logic for the TeacherApiServicer
// This service should implement the business logic for every endpoint for the TeacherApi API.
// Include any external packages or services that will be required by this service.
type TeacherApiService struct {
}

// NewTeacherApiService creates a default api service
func NewTeacherApiService() TeacherApiServicer {
	return &TeacherApiService{}
}

// TeacherAddClass - teacher adding self to class
func (s *TeacherApiService) TeacherAddClass(ctx context.Context, classesAddAdminBody ClassesAddAdminBody) (ImplResponse, error) {
	// TODO - update TeacherAddClass with the required logic for this service method.
	// Add api_teacher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []InlineResponse20013{}) or use other options such as http.Ok ...
	//return Response(200, []InlineResponse20013{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("TeacherAddClass method not implemented")
}
