/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// StudentApiService is a service that implements the logic for the StudentApiServicer
// This service should implement the business logic for every endpoint for the StudentApi API.
// Include any external packages or services that will be required by this service.
type StudentApiService struct {
}

// NewStudentApiService creates a default api service
func NewStudentApiService() StudentApiServicer {
	return &StudentApiService{}
}

// AuctionBid - auction bid
func (s *StudentApiService) AuctionBid(ctx context.Context, requestAuctionBid RequestAuctionBid) (ImplResponse, error) {
	// TODO - update AuctionBid with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AuctionBid method not implemented")
}

// BuckConvert - When a student is converting between 2 bucks
func (s *StudentApiService) BuckConvert(ctx context.Context, requestBuckConvert RequestBuckConvert) (ImplResponse, error) {
	// TODO - update BuckConvert with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("BuckConvert method not implemented")
}

// BuyCD - When a student is buying a cd
func (s *StudentApiService) BuyCD(ctx context.Context, requestBuyCd RequestBuyCd) (ImplResponse, error) {
	// TODO - update BuyCD with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("BuyCD method not implemented")
}

// CryptoConvert - When a student is converting between uBucks and Cryptos
func (s *StudentApiService) CryptoConvert(ctx context.Context, requestCryptoConvert RequestCryptoConvert) (ImplResponse, error) {
	// TODO - update CryptoConvert with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2001{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2001{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CryptoConvert method not implemented")
}

// LatestLotto - get current lotto game
func (s *StudentApiService) LatestLotto(ctx context.Context) (ImplResponse, error) {
	// TODO - update LatestLotto with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResponseLottoLatest{}) or use other options such as http.Ok ...
	//return Response(200, ResponseLottoLatest{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("LatestLotto method not implemented")
}

// LottoPurchase - purchase lotto ticket
func (s *StudentApiService) LottoPurchase(ctx context.Context, quantity int32) (ImplResponse, error) {
	// TODO - update LottoPurchase with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("LottoPurchase method not implemented")
}

// MarketItemBuy - market purchase
func (s *StudentApiService) MarketItemBuy(ctx context.Context, requestMarketRefund RequestMarketRefund) (ImplResponse, error) {
	// TODO - update MarketItemBuy with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("MarketItemBuy method not implemented")
}

// PreviousLotto - get previous lotto game
func (s *StudentApiService) PreviousLotto(ctx context.Context) (ImplResponse, error) {
	// TODO - update PreviousLotto with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResponseLottoLatest{}) or use other options such as http.Ok ...
	//return Response(200, ResponseLottoLatest{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PreviousLotto method not implemented")
}

// RefundCD - When a student is buying a cd
func (s *StudentApiService) RefundCD(ctx context.Context, requestUser RequestUser) (ImplResponse, error) {
	// TODO - update RefundCD with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RefundCD method not implemented")
}

// SearchAuctionsStudent - searches auctions
func (s *StudentApiService) SearchAuctionsStudent(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchAuctionsStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseAuctionStudent{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseAuctionStudent{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchAuctionsStudent method not implemented")
}

// SearchBuck - returns how much the student holds of this buck
func (s *StudentApiService) SearchBuck(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update SearchBuck with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResponseSearchStudentUbuck{}) or use other options such as http.Ok ...
	//return Response(200, ResponseSearchStudentUbuck{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchBuck method not implemented")
}

// SearchBuckTransactions - searches for buck transactions
func (s *StudentApiService) SearchBuckTransactions(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchBuckTransactions with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseBuckTransaction{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseBuckTransaction{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchBuckTransactions method not implemented")
}

// SearchCDS - returns active certificate of deposit portfolio
func (s *StudentApiService) SearchCDS(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchCDS with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseCd{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseCd{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchCDS method not implemented")
}

// SearchCDTransactions - searches for CD transactions
func (s *StudentApiService) SearchCDTransactions(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchCDTransactions with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseTransactions{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseTransactions{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchCDTransactions method not implemented")
}

// SearchCrypto - returns the given crypto price, how many are owned and how many ubucks the user has.
func (s *StudentApiService) SearchCrypto(ctx context.Context, name string) (ImplResponse, error) {
	// TODO - update SearchCrypto with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResponseCrypto{}) or use other options such as http.Ok ...
	//return Response(200, ResponseCrypto{}), nil

	//TODO: Uncomment the next line to return response Response(404, InlineResponse404{}) or use other options such as http.Ok ...
	//return Response(404, InlineResponse404{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchCrypto method not implemented")
}

// SearchCryptoTransaction - searches for Crypto transactions
func (s *StudentApiService) SearchCryptoTransaction(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchCryptoTransaction with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseCryptoTransaction{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseCryptoTransaction{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchCryptoTransaction method not implemented")
}

// SearchStudentCrypto - returns all crypto accounts for specific user
func (s *StudentApiService) SearchStudentCrypto(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchStudentCrypto with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Crypto{}) or use other options such as http.Ok ...
	//return Response(200, []Crypto{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchStudentCrypto method not implemented")
}

// SearchStudentUbuck - searches accounts for UBuck for this student at this school
func (s *StudentApiService) SearchStudentUbuck(ctx context.Context) (ImplResponse, error) {
	// TODO - update SearchStudentUbuck with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ResponseSearchStudentUbuck{}) or use other options such as http.Ok ...
	//return Response(200, ResponseSearchStudentUbuck{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchStudentUbuck method not implemented")
}

// StudentAddClass - student adding self to class
func (s *StudentApiService) StudentAddClass(ctx context.Context, requestAddClass RequestAddClass) (ImplResponse, error) {
	// TODO - update StudentAddClass with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ResponseMemberClass{}) or use other options such as http.Ok ...
	//return Response(200, []ResponseMemberClass{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("StudentAddClass method not implemented")
}
