/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// SchoolAdminApiController binds http requests to an api service and writes the service results to the http response
type SchoolAdminApiController struct {
	service      SchoolAdminApiServicer
	errorHandler ErrorHandler
}

// SchoolAdminApiOption for how the controller is set up.
type SchoolAdminApiOption func(*SchoolAdminApiController)

// WithSchoolAdminApiErrorHandler inject ErrorHandler into controller
func WithSchoolAdminApiErrorHandler(h ErrorHandler) SchoolAdminApiOption {
	return func(c *SchoolAdminApiController) {
		c.errorHandler = h
	}
}

// NewSchoolAdminApiController creates a default api controller
func NewSchoolAdminApiController(s SchoolAdminApiServicer, opts ...SchoolAdminApiOption) Router {
	controller := &SchoolAdminApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all of the api route for the SchoolAdminApiController
func (c *SchoolAdminApiController) Routes() Routes {
	return Routes{
		{
			"ExecuteTax",
			strings.ToUpper("Post"),
			"/api/schools/school/tax",
			c.ExecuteTax,
		},
		{
			"GetStudentCount",
			strings.ToUpper("Get"),
			"/api/schools/school/count",
			c.GetStudentCount,
		},
		{
			"ProgressiveBrackets",
			strings.ToUpper("Get"),
			"/api/schools/school/tax",
			c.ProgressiveBrackets,
		},
		{
			"SearchAdminTeacherClass",
			strings.ToUpper("Get"),
			"/api/classes/teachers",
			c.SearchAdminTeacherClass,
		},
	}
}

// ExecuteTax - When a school admin taxes
func (c *SchoolAdminApiController) ExecuteTax(w http.ResponseWriter, r *http.Request) {
	requestTaxParam := RequestTax{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&requestTaxParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRequestTaxRequired(requestTaxParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ExecuteTax(r.Context(), requestTaxParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetStudentCount - gets student count for a school
func (c *SchoolAdminApiController) GetStudentCount(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	schoolIdParam := query.Get("schoolId")
	result, err := c.service.GetStudentCount(r.Context(), schoolIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ProgressiveBrackets - to get the tax brackets of a progressive tax
func (c *SchoolAdminApiController) ProgressiveBrackets(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ProgressiveBrackets(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// SearchAdminTeacherClass - gets the teacher class of an admin and all the teacher that are its members
func (c *SchoolAdminApiController) SearchAdminTeacherClass(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	idParam := query.Get("_id")
	result, err := c.service.SearchAdminTeacherClass(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
