/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AllSchoolApiService is a service that implements the logic for the AllSchoolApiServicer
// This service should implement the business logic for every endpoint for the AllSchoolApi API.
// Include any external packages or services that will be required by this service.
type AllSchoolApiService struct {
}

// NewAllSchoolApiService creates a default api service
func NewAllSchoolApiService() AllSchoolApiServicer {
	return &AllSchoolApiService{}
}

// AddCodeClass - change class addCode
func (s *AllSchoolApiService) AddCodeClass(ctx context.Context, classAddCodeBody ClassAddCodeBody) (ImplResponse, error) {
	// TODO - update AddCodeClass with the required logic for this service method.
	// Add api_all_school_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Class{}) or use other options such as http.Ok ...
	//return Response(200, Class{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddCodeClass method not implemented")
}

// RemoveClass - remove self from class
func (s *AllSchoolApiService) RemoveClass(ctx context.Context, classesRemoveAdminBody ClassesRemoveAdminBody) (ImplResponse, error) {
	// TODO - update RemoveClass with the required logic for this service method.
	// Add api_all_school_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []InlineResponse20012{}) or use other options such as http.Ok ...
	//return Response(200, []InlineResponse20012{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RemoveClass method not implemented")
}

// SearchAuctions - searches auctions
func (s *AllSchoolApiService) SearchAuctions(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update SearchAuctions with the required logic for this service method.
	// Add api_all_school_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Auction{}) or use other options such as http.Ok ...
	//return Response(200, []Auction{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchAuctions method not implemented")
}

// SearchMyClasses - searches for users classes that the requester is a member of
func (s *AllSchoolApiService) SearchMyClasses(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update SearchMyClasses with the required logic for this service method.
	// Add api_all_school_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []InlineResponse20011{}) or use other options such as http.Ok ...
	//return Response(200, []InlineResponse20011{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchMyClasses method not implemented")
}
