/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Settings struct {

	Student2student bool `json:"student2student,omitempty"`

	CurrencyLock bool `json:"CurrencyLock,omitempty"`
}

// AssertSettingsRequired checks if the required fields are not zero-ed
func AssertSettingsRequired(obj Settings) error {
	return nil
}

// AssertRecurseSettingsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Settings (e.g. [][]Settings), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSettingsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSettings, ok := obj.(Settings)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSettingsRequired(aSettings)
	})
}
