/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseKickClass struct {

	KickId string `json:"kick_id,omitempty"`
}

// AssertResponseKickClassRequired checks if the required fields are not zero-ed
func AssertResponseKickClassRequired(obj ResponseKickClass) error {
	return nil
}

// AssertRecurseResponseKickClassRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseKickClass (e.g. [][]ResponseKickClass), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseKickClassRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseKickClass, ok := obj.(ResponseKickClass)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseKickClassRequired(aResponseKickClass)
	})
}
