/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2006 struct {

	Transaction InlineResponse2006Transaction `json:"transaction,omitempty"`

	Accounts []InlineResponse2006Accounts `json:"accounts,omitempty"`
}

// AssertInlineResponse2006Required checks if the required fields are not zero-ed
func AssertInlineResponse2006Required(obj InlineResponse2006) error {
	if err := AssertInlineResponse2006TransactionRequired(obj.Transaction); err != nil {
		return err
	}
	for _, el := range obj.Accounts {
		if err := AssertInlineResponse2006AccountsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInlineResponse2006Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2006 (e.g. [][]InlineResponse2006), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2006Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2006, ok := obj.(InlineResponse2006)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2006Required(aInlineResponse2006)
	})
}
