/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseMakeAuctionWinner struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertResponseMakeAuctionWinnerRequired checks if the required fields are not zero-ed
func AssertResponseMakeAuctionWinnerRequired(obj ResponseMakeAuctionWinner) error {
	return nil
}

// AssertRecurseResponseMakeAuctionWinnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseMakeAuctionWinner (e.g. [][]ResponseMakeAuctionWinner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseMakeAuctionWinnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseMakeAuctionWinner, ok := obj.(ResponseMakeAuctionWinner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseMakeAuctionWinnerRequired(aResponseMakeAuctionWinner)
	})
}
