/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestEditClass struct {
	Name string `json:"name,omitempty"`

	Period int32 `json:"period,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertRequestEditClassRequired checks if the required fields are not zero-ed
func AssertRequestEditClassRequired(obj RequestEditClass) error {
	return nil
}

// AssertRecurseRequestEditClassRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestEditClass (e.g. [][]RequestEditClass), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestEditClassRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestEditClass, ok := obj.(RequestEditClass)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestEditClassRequired(aRequestEditClass)
	})
}
