/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BucksBuckBody1 struct {

	Name string `json:"name,omitempty"`

	Owner string `json:"owner,omitempty"`

	School string `json:"school,omitempty"`
}

// AssertBucksBuckBody1Required checks if the required fields are not zero-ed
func AssertBucksBuckBody1Required(obj BucksBuckBody1) error {
	return nil
}

// AssertRecurseBucksBuckBody1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BucksBuckBody1 (e.g. [][]BucksBuckBody1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBucksBuckBody1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBucksBuckBody1, ok := obj.(BucksBuckBody1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBucksBuckBody1Required(aBucksBuckBody1)
	})
}
