/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20010Accounts struct {

	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse20010AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse20010AccountsRequired(obj InlineResponse20010Accounts) error {
	return nil
}

// AssertRecurseInlineResponse20010AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20010Accounts (e.g. [][]InlineResponse20010Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20010AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20010Accounts, ok := obj.(InlineResponse20010Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20010AccountsRequired(aInlineResponse20010Accounts)
	})
}
