/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseCookie struct {

	WAuthExp string `json:"w_authExp,omitempty"`

	WAuth string `json:"w_auth,omitempty"`
}

// AssertResponseCookieRequired checks if the required fields are not zero-ed
func AssertResponseCookieRequired(obj ResponseCookie) error {
	return nil
}

// AssertRecurseResponseCookieRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseCookie (e.g. [][]ResponseCookie), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseCookieRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseCookie, ok := obj.(ResponseCookie)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseCookieRequired(aResponseCookie)
	})
}
