/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2008 struct {

	Transaction InlineResponse2008Transaction `json:"transaction,omitempty"`

	Accounts []InlineResponse2008Accounts `json:"accounts,omitempty"`
}

// AssertInlineResponse2008Required checks if the required fields are not zero-ed
func AssertInlineResponse2008Required(obj InlineResponse2008) error {
	if err := AssertInlineResponse2008TransactionRequired(obj.Transaction); err != nil {
		return err
	}
	for _, el := range obj.Accounts {
		if err := AssertInlineResponse2008AccountsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInlineResponse2008Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2008 (e.g. [][]InlineResponse2008), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2008Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2008, ok := obj.(InlineResponse2008)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2008Required(aInlineResponse2008)
	})
}
