/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20019 struct {
	Deleted bool `json:"deleted,omitempty"`
}

// AssertInlineResponse20019Required checks if the required fields are not zero-ed
func AssertInlineResponse20019Required(obj InlineResponse20019) error {
	return nil
}

// AssertRecurseInlineResponse20019Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20019 (e.g. [][]InlineResponse20019), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20019Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20019, ok := obj.(InlineResponse20019)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20019Required(aInlineResponse20019)
	})
}
