/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2008AssetId struct {
	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2008AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2008AssetIdRequired(obj InlineResponse2008AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2008AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2008AssetId (e.g. [][]InlineResponse2008AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2008AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2008AssetId, ok := obj.(InlineResponse2008AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2008AssetIdRequired(aInlineResponse2008AssetId)
	})
}
