/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClassesRemoveAdminBody struct {
	KickId string `json:"kick_id,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertClassesRemoveAdminBodyRequired checks if the required fields are not zero-ed
func AssertClassesRemoveAdminBodyRequired(obj ClassesRemoveAdminBody) error {
	return nil
}

// AssertRecurseClassesRemoveAdminBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ClassesRemoveAdminBody (e.g. [][]ClassesRemoveAdminBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseClassesRemoveAdminBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aClassesRemoveAdminBody, ok := obj.(ClassesRemoveAdminBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertClassesRemoveAdminBodyRequired(aClassesRemoveAdminBody)
	})
}
