/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseAuctionStudentWinner struct {

	Id string `json:"_id,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertResponseAuctionStudentWinnerRequired checks if the required fields are not zero-ed
func AssertResponseAuctionStudentWinnerRequired(obj ResponseAuctionStudentWinner) error {
	return nil
}

// AssertRecurseResponseAuctionStudentWinnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseAuctionStudentWinner (e.g. [][]ResponseAuctionStudentWinner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseAuctionStudentWinnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseAuctionStudentWinner, ok := obj.(ResponseAuctionStudentWinner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseAuctionStudentWinnerRequired(aResponseAuctionStudentWinner)
	})
}
