/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseXRate struct {

	Conversion float32 `json:"conversion,omitempty"`

	Bucks string `json:"bucks,omitempty"`

	Balance float32 `json:"balance,omitempty"`

	Id string `json:"_id,omitempty"`

	TypeId string `json:"type_id,omitempty"`
}

// AssertResponseXRateRequired checks if the required fields are not zero-ed
func AssertResponseXRateRequired(obj ResponseXRate) error {
	return nil
}

// AssertRecurseResponseXRateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseXRate (e.g. [][]ResponseXRate), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseXRateRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseXRate, ok := obj.(ResponseXRate)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseXRateRequired(aResponseXRate)
	})
}
