/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestBuckConvert struct {

	AccountFrom string `json:"accountFrom,omitempty"`

	AccountTo string `json:"accountTo,omitempty"`

	Amount float32 `json:"amount,omitempty"`
}

// AssertRequestBuckConvertRequired checks if the required fields are not zero-ed
func AssertRequestBuckConvertRequired(obj RequestBuckConvert) error {
	return nil
}

// AssertRecurseRequestBuckConvertRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestBuckConvert (e.g. [][]RequestBuckConvert), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestBuckConvertRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestBuckConvert, ok := obj.(RequestBuckConvert)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestBuckConvertRequired(aRequestBuckConvert)
	})
}
