/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseMarketPurchases struct {

	Count int32 `json:"count,omitempty"`
}

// AssertResponseMarketPurchasesRequired checks if the required fields are not zero-ed
func AssertResponseMarketPurchasesRequired(obj ResponseMarketPurchases) error {
	return nil
}

// AssertRecurseResponseMarketPurchasesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseMarketPurchases (e.g. [][]ResponseMarketPurchases), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseMarketPurchasesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseMarketPurchases, ok := obj.(ResponseMarketPurchases)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseMarketPurchasesRequired(aResponseMarketPurchases)
	})
}
