/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccountsAccountBody1 struct {

	Owner string `json:"owner,omitempty"`

	Kind string `json:"kind,omitempty"`

	Type string `json:"type,omitempty"`

	Value float32 `json:"value,omitempty"`

	Basis float32 `json:"basis,omitempty"`
}

// AssertAccountsAccountBody1Required checks if the required fields are not zero-ed
func AssertAccountsAccountBody1Required(obj AccountsAccountBody1) error {
	return nil
}

// AssertRecurseAccountsAccountBody1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccountsAccountBody1 (e.g. [][]AccountsAccountBody1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccountsAccountBody1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccountsAccountBody1, ok := obj.(AccountsAccountBody1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccountsAccountBody1Required(aAccountsAccountBody1)
	})
}
