/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TransactionsPayTransactionsBody struct {

	Owner string `json:"owner,omitempty"`

	Description string `json:"description,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Student string `json:"student,omitempty"`

	Kind string `json:"kind,omitempty"`
}

// AssertTransactionsPayTransactionsBodyRequired checks if the required fields are not zero-ed
func AssertTransactionsPayTransactionsBodyRequired(obj TransactionsPayTransactionsBody) error {
	return nil
}

// AssertRecurseTransactionsPayTransactionsBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TransactionsPayTransactionsBody (e.g. [][]TransactionsPayTransactionsBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTransactionsPayTransactionsBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTransactionsPayTransactionsBody, ok := obj.(TransactionsPayTransactionsBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTransactionsPayTransactionsBodyRequired(aTransactionsPayTransactionsBody)
	})
}
