/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type UnifiedAuction struct {

	Id time.Time `json:"_id"`

	Bid float32 `json:"bid"`

	Description string `json:"description"`

	EndDate time.Time `json:"endDate"`

	StartDate time.Time `json:"startDate"`

	Active bool `json:"active"`

	Approved bool `json:"approved"`

	Approver string `json:"approver,omitempty"`

	OwnerId UnifiedAuctionOwnerId `json:"owner_id,omitempty"`

	WinnerId UnifiedAuctionOwnerId `json:"winner_id,omitempty"`

	MaxBid int32 `json:"maxBid,omitempty"`

	TrueAuction bool `json:"trueAuction,omitempty"`

	Visibility []string `json:"visibility,omitempty"`
}

// AssertUnifiedAuctionRequired checks if the required fields are not zero-ed
func AssertUnifiedAuctionRequired(obj UnifiedAuction) error {
	elements := map[string]interface{}{
		"_id": obj.Id,
		"bid": obj.Bid,
		"description": obj.Description,
		"endDate": obj.EndDate,
		"startDate": obj.StartDate,
		"active": obj.Active,
		"approved": obj.Approved,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUnifiedAuctionOwnerIdRequired(obj.OwnerId); err != nil {
		return err
	}
	if err := AssertUnifiedAuctionOwnerIdRequired(obj.WinnerId); err != nil {
		return err
	}
	return nil
}

// AssertRecurseUnifiedAuctionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UnifiedAuction (e.g. [][]UnifiedAuction), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUnifiedAuctionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUnifiedAuction, ok := obj.(UnifiedAuction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUnifiedAuctionRequired(aUnifiedAuction)
	})
}
