/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2003TransactionAssetId struct {

	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertInlineResponse2003TransactionAssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2003TransactionAssetIdRequired(obj InlineResponse2003TransactionAssetId) error {
	return nil
}

// AssertRecurseInlineResponse2003TransactionAssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2003TransactionAssetId (e.g. [][]InlineResponse2003TransactionAssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2003TransactionAssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2003TransactionAssetId, ok := obj.(InlineResponse2003TransactionAssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2003TransactionAssetIdRequired(aInlineResponse2003TransactionAssetId)
	})
}
