/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2006 struct {

	Account string `json:"account,omitempty"`

	Owner string `json:"owner,omitempty"`

	Balance float32 `json:"balance,omitempty"`

	Description string `json:"description,omitempty"`

	ConversionRatio float32 `json:"conversionRatio,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	UBucks float32 `json:"uBucks,omitempty"`

	Type string `json:"type,omitempty"`

	AssetID InlineResponse2006AssetId `json:"assetID,omitempty"`
}

// AssertInlineResponse2006Required checks if the required fields are not zero-ed
func AssertInlineResponse2006Required(obj InlineResponse2006) error {
	if err := AssertInlineResponse2006AssetIdRequired(obj.AssetID); err != nil {
		return err
	}
	return nil
}

// AssertRecurseInlineResponse2006Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2006 (e.g. [][]InlineResponse2006), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2006Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2006, ok := obj.(InlineResponse2006)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2006Required(aInlineResponse2006)
	})
}
