/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20019AssetId struct {
	Name string `json:"name,omitempty"`
}

// AssertInlineResponse20019AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse20019AssetIdRequired(obj InlineResponse20019AssetId) error {
	return nil
}

// AssertRecurseInlineResponse20019AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20019AssetId (e.g. [][]InlineResponse20019AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20019AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20019AssetId, ok := obj.(InlineResponse20019AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20019AssetIdRequired(aInlineResponse20019AssetId)
	})
}
