/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20021 struct {
	Deleted bool `json:"deleted,omitempty"`
}

// AssertInlineResponse20021Required checks if the required fields are not zero-ed
func AssertInlineResponse20021Required(obj InlineResponse20021) error {
	return nil
}

// AssertRecurseInlineResponse20021Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20021 (e.g. [][]InlineResponse20021), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20021Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20021, ok := obj.(InlineResponse20021)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20021Required(aInlineResponse20021)
	})
}
