/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UsersUserBody struct {
	Email string `json:"email,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Password string `json:"password,omitempty"`

	College bool `json:"college,omitempty"`

	CareerTransition bool `json:"careerTransition,omitempty"`
}

// AssertUsersUserBodyRequired checks if the required fields are not zero-ed
func AssertUsersUserBodyRequired(obj UsersUserBody) error {
	return nil
}

// AssertRecurseUsersUserBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UsersUserBody (e.g. [][]UsersUserBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUsersUserBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUsersUserBody, ok := obj.(UsersUserBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUsersUserBodyRequired(aUsersUserBody)
	})
}
