/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20020TransactionAssetId struct {
	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertInlineResponse20020TransactionAssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse20020TransactionAssetIdRequired(obj InlineResponse20020TransactionAssetId) error {
	return nil
}

// AssertRecurseInlineResponse20020TransactionAssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20020TransactionAssetId (e.g. [][]InlineResponse20020TransactionAssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20020TransactionAssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20020TransactionAssetId, ok := obj.(InlineResponse20020TransactionAssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20020TransactionAssetIdRequired(aInlineResponse20020TransactionAssetId)
	})
}
