/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse4041 struct {
	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertInlineResponse4041Required checks if the required fields are not zero-ed
func AssertInlineResponse4041Required(obj InlineResponse4041) error {
	return nil
}

// AssertRecurseInlineResponse4041Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse4041 (e.g. [][]InlineResponse4041), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse4041Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse4041, ok := obj.(InlineResponse4041)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse4041Required(aInlineResponse4041)
	})
}
