/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccountsAccountBody struct {

	Id string `json:"_id,omitempty"`

	Owner string `json:"owner,omitempty"`

	Kind string `json:"kind,omitempty"`

	Type string `json:"type,omitempty"`

	Value float32 `json:"value,omitempty"`

	Basis float32 `json:"basis,omitempty"`
}

// AssertAccountsAccountBodyRequired checks if the required fields are not zero-ed
func AssertAccountsAccountBodyRequired(obj AccountsAccountBody) error {
	return nil
}

// AssertRecurseAccountsAccountBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccountsAccountBody (e.g. [][]AccountsAccountBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAccountsAccountBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccountsAccountBody, ok := obj.(AccountsAccountBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAccountsAccountBodyRequired(aAccountsAccountBody)
	})
}
