/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2004AssetId struct {

	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2004AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2004AssetIdRequired(obj InlineResponse2004AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2004AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2004AssetId (e.g. [][]InlineResponse2004AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2004AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2004AssetId, ok := obj.(InlineResponse2004AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2004AssetIdRequired(aInlineResponse2004AssetId)
	})
}
