/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestLogin struct {

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`
}

// AssertRequestLoginRequired checks if the required fields are not zero-ed
func AssertRequestLoginRequired(obj RequestLogin) error {
	return nil
}

// AssertRecurseRequestLoginRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestLogin (e.g. [][]RequestLogin), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestLoginRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestLogin, ok := obj.(RequestLogin)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestLoginRequired(aRequestLogin)
	})
}
