/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestPayTransactions struct {

	Owner string `json:"owner,omitempty"`

	Description string `json:"description,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Students []string `json:"students,omitempty"`
}

// AssertRequestPayTransactionsRequired checks if the required fields are not zero-ed
func AssertRequestPayTransactionsRequired(obj RequestPayTransactions) error {
	return nil
}

// AssertRecurseRequestPayTransactionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestPayTransactions (e.g. [][]RequestPayTransactions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestPayTransactionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestPayTransactions, ok := obj.(RequestPayTransactions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestPayTransactionsRequired(aRequestPayTransactions)
	})
}
