/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2003Accounts struct {

	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse2003AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse2003AccountsRequired(obj InlineResponse2003Accounts) error {
	return nil
}

// AssertRecurseInlineResponse2003AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2003Accounts (e.g. [][]InlineResponse2003Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2003AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2003Accounts, ok := obj.(InlineResponse2003Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2003AccountsRequired(aInlineResponse2003Accounts)
	})
}
