/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2007Members struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Rank int32 `json:"rank,omitempty"`

	NetWorth float32 `json:"netWorth,omitempty"`
}

// AssertInlineResponse2007MembersRequired checks if the required fields are not zero-ed
func AssertInlineResponse2007MembersRequired(obj InlineResponse2007Members) error {
	return nil
}

// AssertRecurseInlineResponse2007MembersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2007Members (e.g. [][]InlineResponse2007Members), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2007MembersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2007Members, ok := obj.(InlineResponse2007Members)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2007MembersRequired(aInlineResponse2007Members)
	})
}
