/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Auction struct {

	Id string `json:"_id"`

	OwnerId string `json:"owner_id,omitempty"`

	WinnerId string `json:"winner_id,omitempty"`

	StartDate time.Time `json:"startDate"`

	EndDate time.Time `json:"endDate,omitempty"`

	ItemNumber string `json:"itemNumber"`

	Bid float32 `json:"bid"`

	Description string `json:"description"`

	Visibility []string `json:"visibility"`
}

// AssertAuctionRequired checks if the required fields are not zero-ed
func AssertAuctionRequired(obj Auction) error {
	elements := map[string]interface{}{
		"_id": obj.Id,
		"startDate": obj.StartDate,
		"itemNumber": obj.ItemNumber,
		"bid": obj.Bid,
		"description": obj.Description,
		"visibility": obj.Visibility,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAuctionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Auction (e.g. [][]Auction), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuctionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuction, ok := obj.(Auction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuctionRequired(aAuction)
	})
}
