/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseAccount struct {

	Conversion float32 `json:"conversion,omitempty"`

	History []History `json:"history,omitempty"`

	Buck ResponseAccountBuck `json:"buck,omitempty"`

	Balance float32 `json:"balance,omitempty"`

	Id string `json:"_id,omitempty"`

	TypeId string `json:"type_id,omitempty"`
}

// AssertResponseAccountRequired checks if the required fields are not zero-ed
func AssertResponseAccountRequired(obj ResponseAccount) error {
	for _, el := range obj.History {
		if err := AssertHistoryRequired(el); err != nil {
			return err
		}
	}
	if err := AssertResponseAccountBuckRequired(obj.Buck); err != nil {
		return err
	}
	return nil
}

// AssertRecurseResponseAccountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseAccount (e.g. [][]ResponseAccount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseAccountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseAccount, ok := obj.(ResponseAccount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseAccountRequired(aResponseAccount)
	})
}
