/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestMakeMarketItem struct {

	Title string `json:"title,omitempty"`

	Count int32 `json:"count,omitempty"`

	Cost int32 `json:"cost,omitempty"`
}

// AssertRequestMakeMarketItemRequired checks if the required fields are not zero-ed
func AssertRequestMakeMarketItemRequired(obj RequestMakeMarketItem) error {
	return nil
}

// AssertRecurseRequestMakeMarketItemRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestMakeMarketItem (e.g. [][]RequestMakeMarketItem), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestMakeMarketItemRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestMakeMarketItem, ok := obj.(RequestMakeMarketItem)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestMakeMarketItemRequired(aRequestMakeMarketItem)
	})
}
