/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ResponseCd struct {

	Ts time.Time `json:"Ts,omitempty"`

	Principal int32 `json:"principal,omitempty"`

	CurrentValue float32 `json:"currentValue,omitempty"`

	RefundValue float32 `json:"refundValue,omitempty"`

	Interest float32 `json:"interest,omitempty"`

	Maturity time.Time `json:"maturity,omitempty"`
}

// AssertResponseCdRequired checks if the required fields are not zero-ed
func AssertResponseCdRequired(obj ResponseCd) error {
	return nil
}

// AssertRecurseResponseCdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseCd (e.g. [][]ResponseCd), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseCdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseCd, ok := obj.(ResponseCd)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseCdRequired(aResponseCd)
	})
}
