/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponsePayTransactions struct {

	Message string `json:"message,omitempty"`
}

// AssertResponsePayTransactionsRequired checks if the required fields are not zero-ed
func AssertResponsePayTransactionsRequired(obj ResponsePayTransactions) error {
	return nil
}

// AssertRecurseResponsePayTransactionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponsePayTransactions (e.g. [][]ResponsePayTransactions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponsePayTransactionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponsePayTransactions, ok := obj.(ResponsePayTransactions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponsePayTransactionsRequired(aResponsePayTransactions)
	})
}
