/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2004 struct {

	Success bool `json:"success,omitempty"`
}

// AssertInlineResponse2004Required checks if the required fields are not zero-ed
func AssertInlineResponse2004Required(obj InlineResponse2004) error {
	return nil
}

// AssertRecurseInlineResponse2004Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2004 (e.g. [][]InlineResponse2004), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2004Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2004, ok := obj.(InlineResponse2004)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2004Required(aInlineResponse2004)
	})
}
