/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UnifiedAuctionOwnerId struct {

	Id string `json:"_id,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertUnifiedAuctionOwnerIdRequired checks if the required fields are not zero-ed
func AssertUnifiedAuctionOwnerIdRequired(obj UnifiedAuctionOwnerId) error {
	return nil
}

// AssertRecurseUnifiedAuctionOwnerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UnifiedAuctionOwnerId (e.g. [][]UnifiedAuctionOwnerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUnifiedAuctionOwnerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUnifiedAuctionOwnerId, ok := obj.(UnifiedAuctionOwnerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUnifiedAuctionOwnerIdRequired(aUnifiedAuctionOwnerId)
	})
}
