/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001TransactionAssetId struct {

	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertInlineResponse2001TransactionAssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2001TransactionAssetIdRequired(obj InlineResponse2001TransactionAssetId) error {
	return nil
}

// AssertRecurseInlineResponse2001TransactionAssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2001TransactionAssetId (e.g. [][]InlineResponse2001TransactionAssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2001TransactionAssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2001TransactionAssetId, ok := obj.(InlineResponse2001TransactionAssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2001TransactionAssetIdRequired(aInlineResponse2001TransactionAssetId)
	})
}
