/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseStudentCount struct {

	Count int32 `json:"count,omitempty"`
}

// AssertResponseStudentCountRequired checks if the required fields are not zero-ed
func AssertResponseStudentCountRequired(obj ResponseStudentCount) error {
	return nil
}

// AssertRecurseResponseStudentCountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseStudentCount (e.g. [][]ResponseStudentCount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseStudentCountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseStudentCount, ok := obj.(ResponseStudentCount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseStudentCountRequired(aResponseStudentCount)
	})
}
