/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseMemberClassOwnerId struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertResponseMemberClassOwnerIdRequired checks if the required fields are not zero-ed
func AssertResponseMemberClassOwnerIdRequired(obj ResponseMemberClassOwnerId) error {
	return nil
}

// AssertRecurseResponseMemberClassOwnerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseMemberClassOwnerId (e.g. [][]ResponseMemberClassOwnerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseMemberClassOwnerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseMemberClassOwnerId, ok := obj.(ResponseMemberClassOwnerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseMemberClassOwnerIdRequired(aResponseMemberClassOwnerId)
	})
}
