/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2002Accounts struct {

	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse2002AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse2002AccountsRequired(obj InlineResponse2002Accounts) error {
	return nil
}

// AssertRecurseInlineResponse2002AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2002Accounts (e.g. [][]InlineResponse2002Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2002AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2002Accounts, ok := obj.(InlineResponse2002Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2002AccountsRequired(aInlineResponse2002Accounts)
	})
}
