/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseTeachers struct {

	Id string `json:"_id,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertResponseTeachersRequired checks if the required fields are not zero-ed
func AssertResponseTeachersRequired(obj ResponseTeachers) error {
	return nil
}

// AssertRecurseResponseTeachersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseTeachers (e.g. [][]ResponseTeachers), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseTeachersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseTeachers, ok := obj.(ResponseTeachers)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseTeachersRequired(aResponseTeachers)
	})
}
