/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ResponseTransactionsInner struct {
	Amount float32 `json:"amount,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	Description string `json:"description,omitempty"`

	Student string `json:"student,omitempty"`
}

// AssertResponseTransactionsInnerRequired checks if the required fields are not zero-ed
func AssertResponseTransactionsInnerRequired(obj ResponseTransactionsInner) error {
	return nil
}

// AssertRecurseResponseTransactionsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseTransactionsInner (e.g. [][]ResponseTransactionsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseTransactionsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseTransactionsInner, ok := obj.(ResponseTransactionsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseTransactionsInnerRequired(aResponseTransactionsInner)
	})
}
