/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001AssetId struct {

	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2001AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2001AssetIdRequired(obj InlineResponse2001AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2001AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2001AssetId (e.g. [][]InlineResponse2001AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2001AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2001AssetId, ok := obj.(InlineResponse2001AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2001AssetIdRequired(aInlineResponse2001AssetId)
	})
}
