/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type CryptoCb struct {

	UpdatedAt time.Time `json:"updatedAt"`

	Usd float32 `json:"usd"`
}

// AssertCryptoCbRequired checks if the required fields are not zero-ed
func AssertCryptoCbRequired(obj CryptoCb) error {
	elements := map[string]interface{}{
		"updatedAt": obj.UpdatedAt,
		"usd": obj.Usd,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCryptoCbRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CryptoCb (e.g. [][]CryptoCb), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCryptoCbRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCryptoCb, ok := obj.(CryptoCb)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCryptoCbRequired(aCryptoCb)
	})
}
