/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseAuctionStudentOwnerId struct {

	Id string `json:"_id,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertResponseAuctionStudentOwnerIdRequired checks if the required fields are not zero-ed
func AssertResponseAuctionStudentOwnerIdRequired(obj ResponseAuctionStudentOwnerId) error {
	return nil
}

// AssertRecurseResponseAuctionStudentOwnerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseAuctionStudentOwnerId (e.g. [][]ResponseAuctionStudentOwnerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseAuctionStudentOwnerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseAuctionStudentOwnerId, ok := obj.(ResponseAuctionStudentOwnerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseAuctionStudentOwnerIdRequired(aResponseAuctionStudentOwnerId)
	})
}
