/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2005AssetId struct {

	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2005AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2005AssetIdRequired(obj InlineResponse2005AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2005AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2005AssetId (e.g. [][]InlineResponse2005AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2005AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2005AssetId, ok := obj.(InlineResponse2005AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2005AssetIdRequired(aInlineResponse2005AssetId)
	})
}
