/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseCryptoPrice struct {

	Name string `json:"name,omitempty"`

	Price float32 `json:"price,omitempty"`
}

// AssertResponseCryptoPriceRequired checks if the required fields are not zero-ed
func AssertResponseCryptoPriceRequired(obj ResponseCryptoPrice) error {
	return nil
}

// AssertRecurseResponseCryptoPriceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseCryptoPrice (e.g. [][]ResponseCryptoPrice), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseCryptoPriceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseCryptoPrice, ok := obj.(ResponseCryptoPrice)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseCryptoPriceRequired(aResponseCryptoPrice)
	})
}
