/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestUserEdit struct {

	Email string `json:"email,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Password string `json:"password,omitempty"`

	College bool `json:"college,omitempty"`

	CareerTransition bool `json:"careerTransition,omitempty"`

	LottoPlay int32 `json:"LottoPlay,omitempty"`

	LottoWin int32 `json:"LottoWin,omitempty"`
}

// AssertRequestUserEditRequired checks if the required fields are not zero-ed
func AssertRequestUserEditRequired(obj RequestUserEdit) error {
	return nil
}

// AssertRecurseRequestUserEditRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestUserEdit (e.g. [][]RequestUserEdit), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestUserEditRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestUserEdit, ok := obj.(RequestUserEdit)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestUserEditRequired(aRequestUserEdit)
	})
}
