/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuctionsstudentWinner struct {
	Id string `json:"_id,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertAuctionsstudentWinnerRequired checks if the required fields are not zero-ed
func AssertAuctionsstudentWinnerRequired(obj AuctionsstudentWinner) error {
	return nil
}

// AssertRecurseAuctionsstudentWinnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuctionsstudentWinner (e.g. [][]AuctionsstudentWinner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuctionsstudentWinnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuctionsstudentWinner, ok := obj.(AuctionsstudentWinner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuctionsstudentWinnerRequired(aAuctionsstudentWinner)
	})
}
