/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2002AssetId struct {

	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2002AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2002AssetIdRequired(obj InlineResponse2002AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2002AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2002AssetId (e.g. [][]InlineResponse2002AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2002AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2002AssetId, ok := obj.(InlineResponse2002AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2002AssetIdRequired(aInlineResponse2002AssetId)
	})
}
