/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2007 struct {

	Transaction InlineResponse2007Transaction `json:"transaction,omitempty"`

	Accounts []InlineResponse2007Accounts `json:"accounts,omitempty"`
}

// AssertInlineResponse2007Required checks if the required fields are not zero-ed
func AssertInlineResponse2007Required(obj InlineResponse2007) error {
	if err := AssertInlineResponse2007TransactionRequired(obj.Transaction); err != nil {
		return err
	}
	for _, el := range obj.Accounts {
		if err := AssertInlineResponse2007AccountsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInlineResponse2007Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2007 (e.g. [][]InlineResponse2007), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2007Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2007, ok := obj.(InlineResponse2007)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2007Required(aInlineResponse2007)
	})
}
