/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20020 struct {
	Deleted bool `json:"deleted,omitempty"`
}

// AssertInlineResponse20020Required checks if the required fields are not zero-ed
func AssertInlineResponse20020Required(obj InlineResponse20020) error {
	return nil
}

// AssertRecurseInlineResponse20020Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20020 (e.g. [][]InlineResponse20020), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20020Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20020, ok := obj.(InlineResponse20020)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20020Required(aInlineResponse20020)
	})
}
