/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseAccountBuck struct {

	History []History `json:"history,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertResponseAccountBuckRequired checks if the required fields are not zero-ed
func AssertResponseAccountBuckRequired(obj ResponseAccountBuck) error {
	for _, el := range obj.History {
		if err := AssertHistoryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseResponseAccountBuckRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseAccountBuck (e.g. [][]ResponseAccountBuck), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseAccountBuckRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseAccountBuck, ok := obj.(ResponseAccountBuck)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseAccountBuckRequired(aResponseAccountBuck)
	})
}
