/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestMakeSchool struct {

	School string `json:"school,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	City string `json:"city,omitempty"`

	Zip int32 `json:"zip,omitempty"`

	Email string `json:"email,omitempty"`
}

// AssertRequestMakeSchoolRequired checks if the required fields are not zero-ed
func AssertRequestMakeSchoolRequired(obj RequestMakeSchool) error {
	return nil
}

// AssertRecurseRequestMakeSchoolRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestMakeSchool (e.g. [][]RequestMakeSchool), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestMakeSchoolRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestMakeSchool, ok := obj.(RequestMakeSchool)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestMakeSchoolRequired(aRequestMakeSchool)
	})
}
