/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2005Accounts struct {

	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse2005AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse2005AccountsRequired(obj InlineResponse2005Accounts) error {
	return nil
}

// AssertRecurseInlineResponse2005AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2005Accounts (e.g. [][]InlineResponse2005Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2005AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2005Accounts, ok := obj.(InlineResponse2005Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2005AccountsRequired(aInlineResponse2005Accounts)
	})
}
