/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse4042 struct {
	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertInlineResponse4042Required checks if the required fields are not zero-ed
func AssertInlineResponse4042Required(obj InlineResponse4042) error {
	return nil
}

// AssertRecurseInlineResponse4042Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse4042 (e.g. [][]InlineResponse4042), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse4042Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse4042, ok := obj.(InlineResponse4042)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse4042Required(aInlineResponse4042)
	})
}
