/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestRegister struct {
	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	AddCode string `json:"addCode,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Role int32 `json:"role,omitempty"`
}

// AssertRequestRegisterRequired checks if the required fields are not zero-ed
func AssertRequestRegisterRequired(obj RequestRegister) error {
	return nil
}

// AssertRecurseRequestRegisterRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestRegister (e.g. [][]RequestRegister), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestRegisterRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestRegister, ok := obj.(RequestRegister)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestRegisterRequired(aRequestRegister)
	})
}
