/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClassWithMembersMembers struct {
	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Rank int32 `json:"rank,omitempty"`

	NetWorth float32 `json:"netWorth,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertClassWithMembersMembersRequired checks if the required fields are not zero-ed
func AssertClassWithMembersMembersRequired(obj ClassWithMembersMembers) error {
	return nil
}

// AssertRecurseClassWithMembersMembersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ClassWithMembersMembers (e.g. [][]ClassWithMembersMembers), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseClassWithMembersMembersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aClassWithMembersMembers, ok := obj.(ClassWithMembersMembers)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertClassWithMembersMembersRequired(aClassWithMembersMembers)
	})
}
