/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseEventsOwnerId struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertResponseEventsOwnerIdRequired checks if the required fields are not zero-ed
func AssertResponseEventsOwnerIdRequired(obj ResponseEventsOwnerId) error {
	return nil
}

// AssertRecurseResponseEventsOwnerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseEventsOwnerId (e.g. [][]ResponseEventsOwnerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseEventsOwnerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseEventsOwnerId, ok := obj.(ResponseEventsOwnerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseEventsOwnerIdRequired(aResponseEventsOwnerId)
	})
}
