/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestAddClass struct {
	AddCode string `json:"addCode,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertRequestAddClassRequired checks if the required fields are not zero-ed
func AssertRequestAddClassRequired(obj RequestAddClass) error {
	return nil
}

// AssertRecurseRequestAddClassRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestAddClass (e.g. [][]RequestAddClass), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestAddClassRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestAddClass, ok := obj.(RequestAddClass)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestAddClassRequired(aRequestAddClass)
	})
}
