/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20015 struct {
	Account string `json:"account,omitempty"`

	Owner string `json:"owner,omitempty"`

	Balance float32 `json:"balance,omitempty"`

	Description string `json:"description,omitempty"`

	ConversionRatio float32 `json:"conversionRatio,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	UBucks float32 `json:"uBucks,omitempty"`

	Type string `json:"type,omitempty"`

	AssetID InlineResponse20015AssetId `json:"assetID,omitempty"`
}

// AssertInlineResponse20015Required checks if the required fields are not zero-ed
func AssertInlineResponse20015Required(obj InlineResponse20015) error {
	if err := AssertInlineResponse20015AssetIdRequired(obj.AssetID); err != nil {
		return err
	}
	return nil
}

// AssertRecurseInlineResponse20015Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20015 (e.g. [][]InlineResponse20015), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20015Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20015, ok := obj.(InlineResponse20015)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20015Required(aInlineResponse20015)
	})
}
