/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse404 struct {

	SearchSuccess bool `json:"searchSuccess,omitempty"`

	Message string `json:"message,omitempty"`

	Searched string `json:"searched,omitempty"`

	Usd int32 `json:"usd,omitempty"`

	Owned int32 `json:"owned,omitempty"`

	UBuck float32 `json:"UBuck,omitempty"`
}

// AssertInlineResponse404Required checks if the required fields are not zero-ed
func AssertInlineResponse404Required(obj InlineResponse404) error {
	return nil
}

// AssertRecurseInlineResponse404Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse404 (e.g. [][]InlineResponse404), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse404Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse404, ok := obj.(InlineResponse404)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse404Required(aInlineResponse404)
	})
}
