/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20016AssetId struct {
	Name string `json:"name,omitempty"`
}

// AssertInlineResponse20016AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse20016AssetIdRequired(obj InlineResponse20016AssetId) error {
	return nil
}

// AssertRecurseInlineResponse20016AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20016AssetId (e.g. [][]InlineResponse20016AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20016AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20016AssetId, ok := obj.(InlineResponse20016AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20016AssetIdRequired(aInlineResponse20016AssetId)
	})
}
