/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseEvents struct {

	Value int32 `json:"value,omitempty"`

	Description string `json:"description,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
}

// AssertResponseEventsRequired checks if the required fields are not zero-ed
func AssertResponseEventsRequired(obj ResponseEvents) error {
	return nil
}

// AssertRecurseResponseEventsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseEvents (e.g. [][]ResponseEvents), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseEventsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseEvents, ok := obj.(ResponseEvents)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseEventsRequired(aResponseEvents)
	})
}
