/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseTaxBracket struct {

	Bracket float32 `json:"bracket,omitempty"`

	Rate float32 `json:"rate,omitempty"`
}

// AssertResponseTaxBracketRequired checks if the required fields are not zero-ed
func AssertResponseTaxBracketRequired(obj ResponseTaxBracket) error {
	return nil
}

// AssertRecurseResponseTaxBracketRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseTaxBracket (e.g. [][]ResponseTaxBracket), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseTaxBracketRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseTaxBracket, ok := obj.(ResponseTaxBracket)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseTaxBracketRequired(aResponseTaxBracket)
	})
}
