/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseAuth struct {
	IsAuth bool `json:"isAuth,omitempty"`

	Error bool `json:"error,omitempty"`
}

// AssertResponseAuthRequired checks if the required fields are not zero-ed
func AssertResponseAuthRequired(obj ResponseAuth) error {
	return nil
}

// AssertRecurseResponseAuthRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseAuth (e.g. [][]ResponseAuth), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseAuthRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseAuth, ok := obj.(ResponseAuth)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseAuthRequired(aResponseAuth)
	})
}
