/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestCryptoConvert struct {

	Name string `json:"name,omitempty"`

	Buy float32 `json:"buy,omitempty"`

	Sell float32 `json:"sell,omitempty"`
}

// AssertRequestCryptoConvertRequired checks if the required fields are not zero-ed
func AssertRequestCryptoConvertRequired(obj RequestCryptoConvert) error {
	return nil
}

// AssertRecurseRequestCryptoConvertRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestCryptoConvert (e.g. [][]RequestCryptoConvert), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestCryptoConvertRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestCryptoConvert, ok := obj.(RequestCryptoConvert)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestCryptoConvertRequired(aRequestCryptoConvert)
	})
}
