/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestBuyCd struct {

	PrinInv int32 `json:"prinInv,omitempty"`

	Time int32 `json:"time,omitempty"`
}

// AssertRequestBuyCdRequired checks if the required fields are not zero-ed
func AssertRequestBuyCdRequired(obj RequestBuyCd) error {
	return nil
}

// AssertRecurseRequestBuyCdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestBuyCd (e.g. [][]RequestBuyCd), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestBuyCdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestBuyCd, ok := obj.(RequestBuyCd)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestBuyCdRequired(aRequestBuyCd)
	})
}
