/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20018TransactionAssetId struct {

	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertInlineResponse20018TransactionAssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse20018TransactionAssetIdRequired(obj InlineResponse20018TransactionAssetId) error {
	return nil
}

// AssertRecurseInlineResponse20018TransactionAssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20018TransactionAssetId (e.g. [][]InlineResponse20018TransactionAssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20018TransactionAssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20018TransactionAssetId, ok := obj.(InlineResponse20018TransactionAssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20018TransactionAssetIdRequired(aInlineResponse20018TransactionAssetId)
	})
}
