/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuctionWinnerId struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertAuctionWinnerIdRequired checks if the required fields are not zero-ed
func AssertAuctionWinnerIdRequired(obj AuctionWinnerId) error {
	return nil
}

// AssertRecurseAuctionWinnerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuctionWinnerId (e.g. [][]AuctionWinnerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuctionWinnerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuctionWinnerId, ok := obj.(AuctionWinnerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuctionWinnerIdRequired(aAuctionWinnerId)
	})
}
