/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type AuctionsBody struct {
	Bid float32 `json:"bid,omitempty"`

	Description string `json:"description,omitempty"`

	EndDate time.Time `json:"endDate,omitempty"`

	StartDate time.Time `json:"startDate,omitempty"`

	Owner string `json:"owner,omitempty"`

	Visibility []string `json:"visibility,omitempty"`
}

// AssertAuctionsBodyRequired checks if the required fields are not zero-ed
func AssertAuctionsBodyRequired(obj AuctionsBody) error {
	return nil
}

// AssertRecurseAuctionsBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuctionsBody (e.g. [][]AuctionsBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuctionsBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuctionsBody, ok := obj.(AuctionsBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuctionsBodyRequired(aAuctionsBody)
	})
}
