/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestAuctionBid struct {
	Item string `json:"item,omitempty"`

	Bid int32 `json:"bid,omitempty"`
}

// AssertRequestAuctionBidRequired checks if the required fields are not zero-ed
func AssertRequestAuctionBidRequired(obj RequestAuctionBid) error {
	return nil
}

// AssertRecurseRequestAuctionBidRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RequestAuctionBid (e.g. [][]RequestAuctionBid), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequestAuctionBidRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequestAuctionBid, ok := obj.(RequestAuctionBid)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequestAuctionBidRequired(aRequestAuctionBid)
	})
}
