/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2007TransactionAssetId struct {

	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertInlineResponse2007TransactionAssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2007TransactionAssetIdRequired(obj InlineResponse2007TransactionAssetId) error {
	return nil
}

// AssertRecurseInlineResponse2007TransactionAssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2007TransactionAssetId (e.g. [][]InlineResponse2007TransactionAssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2007TransactionAssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2007TransactionAssetId, ok := obj.(InlineResponse2007TransactionAssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2007TransactionAssetIdRequired(aInlineResponse2007TransactionAssetId)
	})
}
