/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20021Accounts struct {
	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse20021AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse20021AccountsRequired(obj InlineResponse20021Accounts) error {
	return nil
}

// AssertRecurseInlineResponse20021AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20021Accounts (e.g. [][]InlineResponse20021Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20021AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20021Accounts, ok := obj.(InlineResponse20021Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20021AccountsRequired(aInlineResponse20021Accounts)
	})
}
