/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseLogin4 struct {

	LoginSuccess bool `json:"loginSuccess,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertResponseLogin4Required checks if the required fields are not zero-ed
func AssertResponseLogin4Required(obj ResponseLogin4) error {
	return nil
}

// AssertRecurseResponseLogin4Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseLogin4 (e.g. [][]ResponseLogin4), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseLogin4Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseLogin4, ok := obj.(ResponseLogin4)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseLogin4Required(aResponseLogin4)
	})
}
