/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseMakeAuctionVisibility struct {

	Name string `json:"name,omitempty"`
}

// AssertResponseMakeAuctionVisibilityRequired checks if the required fields are not zero-ed
func AssertResponseMakeAuctionVisibilityRequired(obj ResponseMakeAuctionVisibility) error {
	return nil
}

// AssertRecurseResponseMakeAuctionVisibilityRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseMakeAuctionVisibility (e.g. [][]ResponseMakeAuctionVisibility), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseMakeAuctionVisibilityRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseMakeAuctionVisibility, ok := obj.(ResponseMakeAuctionVisibility)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseMakeAuctionVisibilityRequired(aResponseMakeAuctionVisibility)
	})
}
