/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20018 struct {

	Transaction InlineResponse20018Transaction `json:"transaction,omitempty"`

	Accounts []InlineResponse20018Accounts `json:"accounts,omitempty"`
}

// AssertInlineResponse20018Required checks if the required fields are not zero-ed
func AssertInlineResponse20018Required(obj InlineResponse20018) error {
	if err := AssertInlineResponse20018TransactionRequired(obj.Transaction); err != nil {
		return err
	}
	for _, el := range obj.Accounts {
		if err := AssertInlineResponse20018AccountsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseInlineResponse20018Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20018 (e.g. [][]InlineResponse20018), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20018Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20018, ok := obj.(InlineResponse20018)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20018Required(aInlineResponse20018)
	})
}
