/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

type ResponseBuckTransaction struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`

	Balance float32 `json:"balance,omitempty"`

	Description string `json:"description,omitempty"`

	Conversion float32 `json:"conversion,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertResponseBuckTransactionsRequired checks if the required fields are not zero-ed
func AssertResponseBuckTransactionsRequired(obj ResponseBuckTransaction) error {
	return nil
}

// AssertRecurseResponseBuckTransactionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseBuckTransactions (e.g. [][]ResponseBuckTransactions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseBuckTransactionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseBuckTransactions, ok := obj.(ResponseBuckTransaction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseBuckTransactionsRequired(aResponseBuckTransactions)
	})
}
