/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TransactionCryptoTransactionBody struct {

	Name string `json:"name,omitempty"`

	Buy float32 `json:"buy,omitempty"`

	Sell float32 `json:"sell,omitempty"`
}

// AssertTransactionCryptoTransactionBodyRequired checks if the required fields are not zero-ed
func AssertTransactionCryptoTransactionBodyRequired(obj TransactionCryptoTransactionBody) error {
	return nil
}

// AssertRecurseTransactionCryptoTransactionBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TransactionCryptoTransactionBody (e.g. [][]TransactionCryptoTransactionBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTransactionCryptoTransactionBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTransactionCryptoTransactionBody, ok := obj.(TransactionCryptoTransactionBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTransactionCryptoTransactionBodyRequired(aTransactionCryptoTransactionBody)
	})
}
