/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2008Members struct {
	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Rank int32 `json:"rank,omitempty"`

	NetWorth float32 `json:"netWorth,omitempty"`
}

// AssertInlineResponse2008MembersRequired checks if the required fields are not zero-ed
func AssertInlineResponse2008MembersRequired(obj InlineResponse2008Members) error {
	return nil
}

// AssertRecurseInlineResponse2008MembersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2008Members (e.g. [][]InlineResponse2008Members), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2008MembersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2008Members, ok := obj.(InlineResponse2008Members)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2008MembersRequired(aInlineResponse2008Members)
	})
}
