/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponsePayTransaction struct {

	Success bool `json:"success,omitempty"`
}

// AssertResponsePayTransactionRequired checks if the required fields are not zero-ed
func AssertResponsePayTransactionRequired(obj ResponsePayTransaction) error {
	return nil
}

// AssertRecurseResponsePayTransactionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponsePayTransaction (e.g. [][]ResponsePayTransaction), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponsePayTransactionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponsePayTransaction, ok := obj.(ResponsePayTransaction)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponsePayTransactionRequired(aResponsePayTransaction)
	})
}
