/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClassesAddAdminBody struct {

	AddCode string `json:"addCode,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertClassesAddAdminBodyRequired checks if the required fields are not zero-ed
func AssertClassesAddAdminBodyRequired(obj ClassesAddAdminBody) error {
	return nil
}

// AssertRecurseClassesAddAdminBodyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ClassesAddAdminBody (e.g. [][]ClassesAddAdminBody), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseClassesAddAdminBodyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aClassesAddAdminBody, ok := obj.(ClassesAddAdminBody)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertClassesAddAdminBodyRequired(aClassesAddAdminBody)
	})
}
