/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClassesClassBody1 struct {
	Name string `json:"name,omitempty"`

	Owner string `json:"owner,omitempty"`

	Period int32 `json:"period,omitempty"`
}

// AssertClassesClassBody1Required checks if the required fields are not zero-ed
func AssertClassesClassBody1Required(obj ClassesClassBody1) error {
	return nil
}

// AssertRecurseClassesClassBody1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ClassesClassBody1 (e.g. [][]ClassesClassBody1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseClassesClassBody1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aClassesClassBody1, ok := obj.(ClassesClassBody1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertClassesClassBody1Required(aClassesClassBody1)
	})
}
