/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001Accounts struct {

	Basis float32 `json:"basis,omitempty"`

	CurrentPrice float32 `json:"currentPrice,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`
}

// AssertInlineResponse2001AccountsRequired checks if the required fields are not zero-ed
func AssertInlineResponse2001AccountsRequired(obj InlineResponse2001Accounts) error {
	return nil
}

// AssertRecurseInlineResponse2001AccountsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2001Accounts (e.g. [][]InlineResponse2001Accounts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2001AccountsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2001Accounts, ok := obj.(InlineResponse2001Accounts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2001AccountsRequired(aInlineResponse2001Accounts)
	})
}
