/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2006AssetId struct {

	Name string `json:"name,omitempty"`
}

// AssertInlineResponse2006AssetIdRequired checks if the required fields are not zero-ed
func AssertInlineResponse2006AssetIdRequired(obj InlineResponse2006AssetId) error {
	return nil
}

// AssertRecurseInlineResponse2006AssetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2006AssetId (e.g. [][]InlineResponse2006AssetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2006AssetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2006AssetId, ok := obj.(InlineResponse2006AssetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2006AssetIdRequired(aInlineResponse2006AssetId)
	})
}
