/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseSchoolsInner struct {

	Name string `json:"name,omitempty"`

	Id string `json:"_id,omitempty"`
}

// AssertResponseSchoolsInnerRequired checks if the required fields are not zero-ed
func AssertResponseSchoolsInnerRequired(obj ResponseSchoolsInner) error {
	return nil
}

// AssertRecurseResponseSchoolsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseSchoolsInner (e.g. [][]ResponseSchoolsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseSchoolsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseSchoolsInner, ok := obj.(ResponseSchoolsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseSchoolsInnerRequired(aResponseSchoolsInner)
	})
}
