/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Schema struct {

	Id int64 `json:"id,omitempty"`
}

// AssertSchemaRequired checks if the required fields are not zero-ed
func AssertSchemaRequired(obj Schema) error {
	return nil
}

// AssertRecurseSchemaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Schema (e.g. [][]Schema), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSchemaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSchema, ok := obj.(Schema)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSchemaRequired(aSchema)
	})
}
