/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResponseMakeAuctionInnerVisibility struct {

	Name string `json:"name,omitempty"`
}

// AssertResponseMakeAuctionInnerVisibilityRequired checks if the required fields are not zero-ed
func AssertResponseMakeAuctionInnerVisibilityRequired(obj ResponseMakeAuctionInnerVisibility) error {
	return nil
}

// AssertRecurseResponseMakeAuctionInnerVisibilityRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseMakeAuctionInnerVisibility (e.g. [][]ResponseMakeAuctionInnerVisibility), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseMakeAuctionInnerVisibilityRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseMakeAuctionInnerVisibility, ok := obj.(ResponseMakeAuctionInnerVisibility)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseMakeAuctionInnerVisibilityRequired(aResponseMakeAuctionInnerVisibility)
	})
}
