/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.2
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ResponseTransactions struct {

	Amount float32 `json:"amount,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	Description string `json:"description,omitempty"`

	Student string `json:"student,omitempty"`
}

// AssertResponseTransactionsRequired checks if the required fields are not zero-ed
func AssertResponseTransactionsRequired(obj ResponseTransactions) error {
	return nil
}

// AssertRecurseResponseTransactionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseTransactions (e.g. [][]ResponseTransactions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResponseTransactionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseTransactions, ok := obj.(ResponseTransactions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResponseTransactionsRequired(aResponseTransactions)
	})
}
