/*
 * AL
 *
 * This is a simple API
 *
 * API version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20010 struct {

	KickId string `json:"kick_id,omitempty"`
}

// AssertInlineResponse20010Required checks if the required fields are not zero-ed
func AssertInlineResponse20010Required(obj InlineResponse20010) error {
	return nil
}

// AssertRecurseInlineResponse20010Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse20010 (e.g. [][]InlineResponse20010), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse20010Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse20010, ok := obj.(InlineResponse20010)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse20010Required(aInlineResponse20010)
	})
}
