name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o out/ -v ./...

#    - name: Test
#      run: go test -v ./...

    - uses: actions/cache@v2
      id: cache
      with:
        path: out
        key: backend

  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} = 'refs/heads/main'
    needs: build
    environment:
      name: test
    steps:
    - name: deploy-test
      if: steps.cache.outputs.cache-hit != 'true'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.PASS }}
        key: ${{ secrets.KEY }}
        source: "/backend"
        target: ${{ secrets.TARGET }}


