name: Go

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: |
        export CGO_ENABLED=0
        export GOOS=linux
        export GOARCH=amd64
        go build -a -installsuffix cgo -ldflags="-w -s -X main.build_date=$GITHUB_SHA" -o out/backend ./...

    - name: Test
      run: go test -v ./...

    - name: deploy
      if: ${{ github.ref == 'refs/heads/release' }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.PASS }}
        key: ${{ secrets.KEY }}
        source: "out/backend"
        target: ${{ secrets.PROD_TARGET }}

    - name: executing remote ssh commands using ssh key
      if: ${{ github.ref == 'refs/heads/release' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.PASS }}
        key: ${{ secrets.KEY }}
        script: ${{ secrets.SCRIPT }}

